spring:
  application:
    name: processingplatform-local
#  DATABASE CONFIGURATION
  data:
    mongodb:
      # This URI tells Spring to connect to your Atlas cluster
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.et3clgj.mongodb.net/${MONGO_DATABASE_NAME}?retryWrites=true&w=majority&appName=Cluster0

#  LOGGING CONFIGURATION
logging:
  level:
    org:
      springframework:
        security: INFO